import sqlite3

conn = sqlite3.connect('eceDay.db')
cur = conn.cursor()

# Enable foreign key support
cur.execute('PRAGMA foreign_keys = ON;')

cur.execute('''
    CREATE TABLE IF NOT EXISTS teams (
        team_number INTEGER PRIMARY KEY,
        team_name TEXT NOT NULL,
        abstract_summary TEXT,
        team_members TEXT,
        team_client TEXT,
        client_about TEXT,
        team_location TEXT
    )
''')

# Create team_members table
cur.execute('''
    CREATE TABLE IF NOT EXISTS team_members (
        member_id INTEGER PRIMARY KEY AUTOINCREMENT,
        team_member TEXT NOT NULL,
        team_number INTEGER NOT NULL,
        FOREIGN KEY (team_number) REFERENCES teams(team_number) ON DELETE CASCADE
    )
''')

# TODO: Create faculty table? 

# Data
teams_data = [
    (1, 
    'Resource Rally', 
    'A cross platform designed to empower the autistic community through unique accessibility options like dyslexia-friendly fonts and personalized user sensory profiles', 
    'Henry Nguyen, Eirini Theodorakopoulou, Tejas Singh, Colin McDowell', 
    'Sabina Laurino',
    'Project Coordinator for the Center of Autism Research Excellence',
    'Table 1'),
    (2, 
    'ExerSights', 
    'An AI fitness coach that help clients improve their exercise form by leveraging computer vision models to judge movement execution', 
    'Jilin Zheng, James Knee, Anish Sinha, Howell Xia', 
    'Student Defined Project',
    '',
    'Table 2'),
    (3, 
    'AI Coffee Machine', 
    'A centrifugal coffee machine that revolutionizes consistent, high-quality coffee brewing by applying machine learning to automate pressure, temperature, and grind size parameters', 
    'Sebastian Seun, Naomi Gonzalez, Krish Shah, Bryan Zhang', 
    'Kenn Sebesta',
    'Executive Director of the Robotics and Autonomous Systems Technology Innovation Center at Boston University',
    'Table 3'),
    (4, 
    'EdenScope', 
    'An AI-driven plant health monitoring system that detects and diagnoses plant diseases in real time through robotic automation, sensors, and analytics', 
    'Heshan Chen, Yidi Wu, Hailan Gan, Yiwen Wu', 
    'Student Defined Project',
    '',
    'Table 4'),
    (5, 
    'Roomform AI', 
    'Web-based Virtual Interior Design Platform aimed to revolutionize interior design through 3D modelling and augmented reality', 
    'Jack Edelist, Brennan Mahoney, Amruth Niranjan, Zane Mroue', 
    'Student Defined Project',
    '',
    'Table 5'),
    (6, 
    'AI Trading Platform', 
    'Delivers stock insights to assist users with decision making by leveraging machine learning, classification, and reinforcement learning', 
    'Odilon Quevillon, Gabriel Brown, Yagiz Idilman, Adrian Pawlowski', 
    'Student-Defined Project',
    '',
    'Table 6'),
    (7, 
    'Semi-Autonomous Bike for the Visually Impaired', 
    'Tricycle designed to provide independent mobility for visually impaired individuals through self-driving functionality and real-time obstacle detection', 
    'Tara Gill, Cole Resurreccion, Yiran Yin, Jason Calalang, Linden Adamson, Zhilang Gui', 
    'Dan Parker, Professor Eshed Ohn-Bar',
    '',
    'Table 7'),
    (8, 
    'BikeGuard', 
    'A theft prevention system that alarms when lock picking and wire cutting are detected', 
    'Bennett Taylor, Albert Zhao, Beren Yagmur Donmez, Marissa Ruiz, Margherita Piana', 
    'Student-Defined Project',
    '',
    'Table 8'),
    (9, 
    'NeuroToys', 
    'A non-invasive brain-computer interface that converts brainwaves into real-time commands to control a toy car, redefining human-computer interaction', 
    'Andres Marquez Santacruz, Gabriela Porto Machado, Adam Shaikh, Robert Bona, Mete Gumusayak', 
    'Student-Defined Project',
    '',
    'Table 9'),
    (10, 
    'Semi-Autonomous Ground Convoy', 
    'Enabling real time follow the leader behavior for designated targets by applying an integrated vision-aided perception and control system to turtle-bot robots', 
    'Michael Moran, Md Sadman Kabir, Nikhil Krishna, Hugo Silmberg, Benjamin Hsu', 
    'Draper',
    'Nonprofit engineering innovation company',
    'Table 10'),
    (11, 
    'Herd It Here', 
    'An automated cow identification and tracking system, using ear tags image identification', 
    'Chen Zhang, Lucia Gil, Trieu Tran, Cole Knutsen', 
    'Labby Inc.',
    'Provides automatic milk testing for dairy farms',
    'Table 11'),
    (12, 
    'BUtLAR', 
    'Me! A voice-based human-computer interaction system', 
    'Suhani Mitra, Jacqueline Salamy, Noa Margolin, Andrew Sasamori', 
    'Yobe Inc',
    'An Audio A.I. Start-up, providing speaker detection with biometric tracking and other voice-based intelligence services',
    'Table 12'),
    (13, 
    'E-FUNDRAISE', 
    'An AI tool that personalizes fundraiser recommendations to match funding opportunities with researcher profiles', 
    'Carther Theogene, Kevin Chen, Damia Duendar', 
    'Professor Siddharth Ramachandran',
    '',
    'Table 13'),
    (14, 
    'Financial News Service', 
    'An open-source alternative to expensive financial terminals, aimed to democratize access to financial information ', 
    'Ivan Garcia, Rohan Kumar, Harlan Jones, Karl Naba', 
    'Student-Defined Project',
    '',
    'Table 14'),
    (15, 
    'FitnessWatch', 
    'A fitness watch that disperses the hardware around the entirety of the watchband, being uniquely sleek and comfortable', 
    'Zhuowei Chen, John Tran, Youchen Li, Peter West, Carly Butler', 
    'Emily Lam',
    'Co-Founder of R-tangent and Senior Robotics Software Engineer at Sweetgreen',
    'Table 15'),
    (16, 
    'MiniBots', 
    'Aims to replace traditional buoys with anchors to floating, movable bots', 
    'Benjamin Gilbert, Ella Hedman, Noah Robitshek, Eliott Dinfotan, Samuel Kraft', 
    'Professor Thomas Little',
    '',
    'Table 16'),
    (17, 
    'Molecular Dynamics', 
    'Developing optimized, portable FPGA, GPU, and CPU accelerators for molecular dynamics simulations', 
    'Austin Jamias, Vance Raiti, Fadi Kidess, Sora Kakigi, Emika Hamond', 
    'Professor Martin Herbordt',
    '',
    'Table 17'),
    (18, 
    'BU Renew', 
    'Developing a low cost, energy maximizing, and aesthetic solar photovoltaic power system proposal for The College of New Jersey', 
    'Ryan Flynn, Abdulaziz Alrasheed, Gabriel Ferreira, Jeremy Sajda, Lucas McLean', 
    'Student-Defined Project',
    'Entry for the U.S. Department of Energy Solar District Cup Collegiate Design Competition',
    'Table 18'),
    (19, 
    'Personal Alert Device', 
    'A wearable designed for senior citizens to alert medical emergencies, like falling down the stairs', 
    'Logan Lechuga, Richard Yang, Renad Alanazi, Tanveer Dhilon', 
    'Professor Michael Ruane',
    '',
    'Table 19'),
    (20, 
    'Piano Pedals', 
    'A device that depresses piano pedals, designed for pianists that cannot use their legs or feet', 
    "Rohan Alexander Krishnan, Joseph D'Innocenzo, Mallory Cook, Sebastian Gilligan", 
    'Professor Alan Pisano',
    '',
    'Table 20'),
    (21, 
    'LungDetect', 
    'An acoustic imaging system that is capable of detecting and identifying pneumonia-indicative crackles from lung sounds', 
    'Astrid Mihalopoulos, Shadin Almaiman, Matthew Pipko, Phuc Thinh Nguyen, Hilario Gonzalez', 
    'Dr. Andrey Vyshedskiy',
    '',
    'Table 21'),
    (22, 
    'Pollux', 
    'An autonomous countertop cleaning robot, equipped with germicidal sanitization', 
    'Wenhao Cao, Caelan Wong, Louis Cicala, Karl Carisme, Noah Hathout', 
    'Jennifer Remigius',
    'An undergraduate student in the Questrom School of Business',
    'Table 22'),
    (23, 
    'Portable Language Translator', 
    'An all-in-one translation device that enables real-time translation between spoken languages and sign language', 
    'Cristian Palencia, Ryan Liao, Andrew Nguyen, Yohan Kim', 
    'Student-Defined Project',
    '',
    'Table 23'),
    (24, 
    'Rescue 365', 
    'A mobile application that enables users to report new animal rescue cases', 
    'Kenneth Byun, Jayden Raphino, Santos Zuniga, Nicholas Ramondo', 
    'Yasie Saadat',
    'An undergraduate student in the Questrom School of Business',
    'Table 24'),
    (25, 
    'Sailboat Nav', 
    'A mobile app that assists sailors when docking or in crowded areas with various up-to-date sensing capabilities', 
    "Leyandra Burke, Kyla Wilson, Matthew Guacho, Diegonisio D'Angelo-Cosme, Kevin Connell", 
    'Professor Ryan Lagoy',
    '',
    'Table 25'),
    (26, 
    'Simple Sprouts', 
    'An automated vertical farming system designed to optimize plant growth in indoor, controlled environments', 
    'Arthur Hua, Jared Solis, Alex Muntean, Dilhara DeSilva, Sourav Shib', 
    'Student-Defined Project',
    '',
    'Table 26'),
    (27, 
    'Domus', 
    'A smart home and security system that delivers rapid response time and enhanced privacy without cloud dependencies', 
    'Venkata Sai Andra, Vansh Bhatia, Akhil Bongu, Anirudh Singh', 
    'Student-Defined Project',
    '',
    'Table 27'),
    (28, 
    'Machine Learning Powered Electrical Control', 
    'Developing predictive renewable energy generation algorithms for power grids, with the goal of shifting electrical loads to times of peak renewable energy availability', 
    'Mateusz Gorczak, Konstantin Agrachev, Benjamine Axline, Avishai Lean', 
    'Student-Defined Project',
    '',
    'Table 28'),
    (29, 
    'Smart System for Visually Impaired', 
    'A wearable technology that combines obstacle detection, realtime object recognition, auditory feedback, and speech control to assist the visually impaired', 
    'Lukas Chin, Shamir Legaspi, Jake Lee, Jason Li, David Li', 
    'Student-Defined Project',
    '',
    'Table 29'),
    (30, 
    'SmoothOperator', 
    'An interactive robotic assistant designed to autonomously and safely transport luggage in consumer environments, like hospitals', 
    'Eric Chen, Celine Chen, Nicholas Nguyen, Christian So, Jacob Chin', 
    'Student-Defined Project',
    '',
    'Table 30'),
    (31, 
    'OptiView', 
    "An assistive device that aims to combat hearing disability by displaying spoken words on glasses' lenses", 
    'Jialin Sui, Luong Quoc Thai Nguyen, Thinh Phuc Nguyen, Benny Li', 
    'Professor Osama Alshaykh',
    '',
    'Table 31'),
    (32, 
    'Visually Impaired AI Wearable', 
    'An A.I. body camera that provides real-time guidance in the kitchen with text-to-speech feedback', 
    'Houjie Xiong, Louis Jimenez-Hernandez, Heather Li, Dylan Ramadhan', 
    'Student-Defined Project',
    '',
    'Table 32'),
    (33, 
    'Wind Powered Research', 
    'An autonomous vehicle set to navigate around the coast of Southern Massachusetts and Rhode Island without human intervention', 
    'George Cicero, Nyomi Inda, Philip Nied, Mateo Marsella Balzola, Joshua Bardwick', 
    'The Woods Hole Oceanographic Institute',
    "The world's leading independent non-profit dedicated to ocean science",
    'Table 33'),
    (34, 
    'Student Thesis for Microfluidic Chips', 
    'This research presents a microfluidic chip designed to enable real-time monitoring of microbial health using electrochemical impedance spectroscopy', 
    'Woud Alsadoun', 
    'PROFESSORS MIGUEL JIMENEZ & RABIA YAZICIGIL',
    "Part of Boston University's of the Microbial Integration Group",
    'Table 34'),
    (35, 
    'Student Thesis for Protein Expression Optimization', 
    'An AI-driven platform for optimizing protein expression through function-preserving mutations', 
    'Recep Alyamac', 
    'PROFESSOR DOUGLAS DENSMORE',
    'Develops tools for the specification, design, and assembly of synthetic biological systems',
    'Table 35'),
    (36, 
    'Student Thesis for Modifying Transformer Decoding', 
    'A new approach to transformer decoding that integrates the Viterbi algorithm, optimizing text generation by considering both past and future context', 
    'Jivesh Jain', 
    'PROFESSOR BOBAK NAZER',
    'Faculty member in the Department of Electrical and Computer Engineering and affiliated member of the Center for Information & Systems Engineering ',
    'Table 36'),
    (37, 
    'Student Thesis for Physics-Informed Neural Networks', 
    'A physics-informed neural networks aimed to solve complex physical models more efficiently, with various applications like improving heat management in electronic devices and enhancing the accuracy of non-invasive brain imaging', 
    'Wiktor Lidwin', 
    'PROFESSOR LUCA DAL NEGRO',
    'Faculty member in the Department of Electrical and Computer Engineering and in the Material Science Division at Boston University',
    'Table 37'),
    (38, 
    'Student Thesis for Photodetectors and Imagin', 
    'This work aims to design and evaluate metasurface-based photodetectors, leveraging data-driven optimization and angle-resolved photocurrent measurements', 
    'Nicolas Malamug', 
    'ADVISOR: PROFESSOR ROBERTO PAIELLA',
    'Specializes in photonics',
    'Table 38'),
    (39, 
    'Student Thesis for Long-Wave Infrared Detection', 
    'Aiming to address demands for longer-range and highly sensitive infrared radiation detection, like for space exploration and greenhouse gas monitoring, Mercury cadmium telluride has emerged as a premier semiconductor material', 
    'Naeel Quasem', 
    'ADVISOR: PROFESSOR ENRICO BELLOTTI',
    'Member of the Center for Semiconductor Materials & Devices Modeling',
    'Table 39'),
]

cur.executemany('''
    INSERT OR REPLACE INTO teams (team_number, team_name, abstract_summary, team_members, team_client, client_about, team_location)
    VALUES (?, ?, ?, ?, ?, ?, ?)
''', teams_data)

members_data = [
    ('Henry Nguyen', 1), 
    ('Eirini Theodorakopoulou', 1),
    ('Tejas Singh', 1),
    ('Colin McDowell', 1),
    ('Sabina Laurino', 1),

    ('Jilin Zheng', 2), 
    ('James Knee', 2),
    ('Anish Sinha', 2),
    ('Howell Xia', 2),

    ('Sebastian Seun', 3), 
    ('Naomi Gonzalez', 3),
    ('Krish Shah', 3),
    ('Bryan Zhang', 3),
    ('Kenn Sebesta', 3),

    ('Heshan Chen', 4), 
    ('Yidi Wu', 4),
    ('Hailan Gan', 4),
    ('Yiwen Wu', 4),

    ('Jack Edelist', 5), 
    ('Brennan Mahoney', 5),
    ('Amruth Niranjan', 5),
    ('Zane Mroue', 5),

    ('Odilon Quevillon', 6), 
    ('Gabriel Brown', 6),
    ('Yagiz Idilman', 6),
    ('Adrian Pawlowski', 6),

    ('Tara Gill', 7), 
    ('Cole Resurreccion', 7),
    ('Yiran Yin', 7),
    ('Jason Calalang', 7),
    ('Linden Adamson', 7), 
    ('Zhilang Gui', 7),
    (' Dan Parker', 7), 
    ('Professor Eshed Ohn-Bar', 7),

    ('Marissa Ruiz', 8), 
    ('Margherita Piana', 8),
    ('Bennett Taylor', 8),
    ('Albert Zhao', 8),
    ('Beren Yagmur Donmez', 8), 

    ('Andres Marquez Santacruz', 9), 
    ('Gabriela Porto Machado', 9),
    ('Adam Shaikh', 9),
    ('Robert Bona', 9),
    ('Mete Gumusayak', 9), 

    ('Michael Moran', 10), 
    ('Md Sadman Kabir', 10),
    ('Nikhil Krishna', 10),
    ('Hugo Silmberg', 10),
    ('Benjamin Hsu', 10), 

    ('Chen Zhang', 11), 
    ('Lucia Gil', 11),
    ('Trieu Tran', 11),
    ('Cole Knutsen', 11),
    ('Labby Inc.', 11), 

    ('Suhani Mitra', 12), 
    ('Jacqueline Salamy', 12),
    ('Noa Margolin', 12),
    ('Andrew Sasamori', 12),
    ('Yobe Inc.', 12), 

    ('Carther Theogene', 13), 
    ('Kevin Chen', 13),
    ('Damia Duendar', 13),
    ('Siddharth Ramachandran', 13),

    ('Ivan Garcia', 14), 
    ('Rohan Kumar', 14),
    ('Harlan Jones', 14),
    ('Karl Naba', 14),

    ('Zhuowei Chen', 15), 
    ('John Tran', 15),
    ('Youchen Li', 15),
    ('Peter West', 15),
    ('Carly Butler', 15),
    ('Emily Lam', 15),

    ('Benjamin Gilbert', 16), 
    ('Ella Hedman', 16),
    ('Noah Robitshek', 16),
    ('Eliott Dinfotan', 16),
    ('Samuel Kraft', 16),
    ('Professor Thomas Little', 16),

    ('Sora Kakigi', 17), 
    ('Emika Hamond', 17),
    ('Austin Jamias', 17),
    ('Vance Raiti', 17),
    ('Fadi Kidess', 17),
    ('Professor Martin Herbordt', 17),

    ('Ryan Flynn', 18), 
    ('Abdulaziz Alrasheed', 18),
    ('Gabriel Ferreira', 18),
    ('Jeremy Sajda', 18),
    ('Lucas McLean', 18),

    ('Logan Lechuga', 19), 
    ('Richard Yang', 19),
    ('Renad Alanazi', 19),
    ('Tanveer Dhilon', 19),
    ('Professor Michael Ruane', 19),

    ('Rohan Alexander Krishnan', 20), 
    ('Joseph D’Innocenzo', 20),
    ('Mallory Cook', 20),
    ('Sebastian Gilligan', 20),
    ('Professor Alan Pisano', 20),

    ('Astrid Mihalopoulos', 21), 
    ('Shadin Almaiman', 21),
    ('Matthew Pipko', 21),
    ('Phuc Thinh Nguyen', 21),
    ('Hilario Gonzalez', 21),
    ('Dr. Andrey Vyshedskiy', 21),

    ('Wenhao Cao', 22), 
    ('Caelan Wong', 22),
    ('Louis Cicala', 22),
    ('Karl Carisme', 22),
    ('Noah Hathout', 22),
    ('Jennifer Remigius', 22),

    ('Cristian Palencia', 23), 
    ('Ryan Liao', 23),
    ('Andrew Nguyen', 23),
    ('Yohan Kim', 23),

    ('Kenneth Byun', 24), 
    ('Jayden Raphino', 24),
    ('Santos Zuniga', 24),
    ('Nicholas Ramondo', 24),
    ('Yasie Saadat', 24), 

    ('Leyandra Burke', 25), 
    ('Kyla Wilson', 25),
    ('Matthew Guacho', 25),
    ("Diegonisio D'Angelo-Cosme", 25),
    ('Kevin Connell', 25),
    ('Professor Ryan Lagoy', 25),

    ('Arthur Hua', 26), 
    ('Jared Solis', 26),
    ('Alex Muntean', 26),
    ('Dilhara DeSilva', 26),
    ('Sourav Shib', 26),

    ('Venkata Sai Andra', 27), 
    ('Vansh Bhatia', 27),
    ('Akhil Bongu', 27),
    ('Anirudh Singh', 27),

    ('Mateusz Gorczak', 28), 
    ('Konstantin Agrachev', 28),
    ('Benjamine Axline', 28),
    ('Avishai Lean', 28),

    ('Lukas Chin', 29), 
    ('Shamir Legaspi', 29),
    ('Jake Lee', 29),
    ('Jason Li', 29),
    ('David Li', 29), 

    ('Eric Chen', 30), 
    ('Celine Chen', 30),
    ('Nicholas Nguyen', 30),
    ('Christian So', 30),
    ('Jacob Chin', 30), 

    ('Jialin Sui', 31), 
    ('Luong Quoc Thai Nguyen', 31),
    ('Thinh Phuc Nguyen', 31),
    ('Benny Li', 31),
    ('Professor Osama Alshaykh', 31), 

    ('Houjie Xiong', 32), 
    ('Louis Jimenez-Hernandez', 32),
    ('Heather Li', 32),
    ('Dylan Ramadhan', 32),

    ('George Cicero', 32), 
    ('Nyomi Inda', 32),
    ('Philip Nied', 32),
    ('Mateo Marsella Balzola', 32),
    ('Joshua Bardwick', 32), 

    ('Woud Alsadoun', 33), 
    ('Recep Alyamac', 34), 
    ('Jivesh Jain', 35),
    ('Wiktor Lidwin', 36), 
    ('Nicolas Malamug', 37), 
    ('Naeel Quasem', 39),


]

cur.executemany('INSERT INTO team_members (team_member, team_number) VALUES (?, ?)', members_data)

# Commit the changes
conn.commit()

# Example query: Where is Noa's table?
cur.execute('''
    SELECT t.team_name, t.team_location
    FROM teams t
    JOIN team_members tm ON t.team_number = tm.team_number
    WHERE tm.team_member = ?
''', ('Jacob Chin',))
result = cur.fetchone()
if result:
    print(f"Jacobs's team: {result[0]}, Location: {result[1]}")
else:
    print("Jacob not found.")

# Close the connection
conn.close()

print("Database created and data inserted successfully!")